# Generated by Django 4.2.1 on 2023-08-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='ScName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
